
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GuildChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model GuildChannel
 * 
 */
export type GuildChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$GuildChannelPayload>

export type AggregateGuildChannel = {
  _count: GuildChannelCountAggregateOutputType | null
  _min: GuildChannelMinAggregateOutputType | null
  _max: GuildChannelMaxAggregateOutputType | null
}

export type GuildChannelMinAggregateOutputType = {
  name: string | null
  id: string | null
  url: string | null
  guildId: string | null
}

export type GuildChannelMaxAggregateOutputType = {
  name: string | null
  id: string | null
  url: string | null
  guildId: string | null
}

export type GuildChannelCountAggregateOutputType = {
  name: number
  id: number
  url: number
  guildId: number
  _all: number
}


export type GuildChannelMinAggregateInputType = {
  name?: true
  id?: true
  url?: true
  guildId?: true
}

export type GuildChannelMaxAggregateInputType = {
  name?: true
  id?: true
  url?: true
  guildId?: true
}

export type GuildChannelCountAggregateInputType = {
  name?: true
  id?: true
  url?: true
  guildId?: true
  _all?: true
}

export type GuildChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuildChannel to aggregate.
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildChannels to fetch.
   */
  orderBy?: Prisma.GuildChannelOrderByWithRelationInput | Prisma.GuildChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuildChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GuildChannels
  **/
  _count?: true | GuildChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuildChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuildChannelMaxAggregateInputType
}

export type GetGuildChannelAggregateType<T extends GuildChannelAggregateArgs> = {
      [P in keyof T & keyof AggregateGuildChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuildChannel[P]>
    : Prisma.GetScalarType<T[P], AggregateGuildChannel[P]>
}




export type GuildChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuildChannelWhereInput
  orderBy?: Prisma.GuildChannelOrderByWithAggregationInput | Prisma.GuildChannelOrderByWithAggregationInput[]
  by: Prisma.GuildChannelScalarFieldEnum[] | Prisma.GuildChannelScalarFieldEnum
  having?: Prisma.GuildChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GuildChannelCountAggregateInputType | true
  _min?: GuildChannelMinAggregateInputType
  _max?: GuildChannelMaxAggregateInputType
}

export type GuildChannelGroupByOutputType = {
  name: string
  id: string
  url: string
  guildId: string
  _count: GuildChannelCountAggregateOutputType | null
  _min: GuildChannelMinAggregateOutputType | null
  _max: GuildChannelMaxAggregateOutputType | null
}

type GetGuildChannelGroupByPayload<T extends GuildChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuildChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuildChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuildChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuildChannelGroupByOutputType[P]>
      }
    >
  >



export type GuildChannelWhereInput = {
  AND?: Prisma.GuildChannelWhereInput | Prisma.GuildChannelWhereInput[]
  OR?: Prisma.GuildChannelWhereInput[]
  NOT?: Prisma.GuildChannelWhereInput | Prisma.GuildChannelWhereInput[]
  name?: Prisma.StringFilter<"GuildChannel"> | string
  id?: Prisma.StringFilter<"GuildChannel"> | string
  url?: Prisma.StringFilter<"GuildChannel"> | string
  guildId?: Prisma.StringFilter<"GuildChannel"> | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}

export type GuildChannelOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  guild?: Prisma.GuildOrderByWithRelationInput
}

export type GuildChannelWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.GuildChannelWhereInput | Prisma.GuildChannelWhereInput[]
  OR?: Prisma.GuildChannelWhereInput[]
  NOT?: Prisma.GuildChannelWhereInput | Prisma.GuildChannelWhereInput[]
  id?: Prisma.StringFilter<"GuildChannel"> | string
  url?: Prisma.StringFilter<"GuildChannel"> | string
  guildId?: Prisma.StringFilter<"GuildChannel"> | string
  guild?: Prisma.XOR<Prisma.GuildScalarRelationFilter, Prisma.GuildWhereInput>
}, "name">

export type GuildChannelOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
  _count?: Prisma.GuildChannelCountOrderByAggregateInput
  _max?: Prisma.GuildChannelMaxOrderByAggregateInput
  _min?: Prisma.GuildChannelMinOrderByAggregateInput
}

export type GuildChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuildChannelScalarWhereWithAggregatesInput | Prisma.GuildChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.GuildChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GuildChannelScalarWhereWithAggregatesInput | Prisma.GuildChannelScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"GuildChannel"> | string
  id?: Prisma.StringWithAggregatesFilter<"GuildChannel"> | string
  url?: Prisma.StringWithAggregatesFilter<"GuildChannel"> | string
  guildId?: Prisma.StringWithAggregatesFilter<"GuildChannel"> | string
}

export type GuildChannelCreateInput = {
  name: string
  id: string
  url: string
  guild: Prisma.GuildCreateNestedOneWithoutChannelsInput
}

export type GuildChannelUncheckedCreateInput = {
  name: string
  id: string
  url: string
  guildId: string
}

export type GuildChannelUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  guild?: Prisma.GuildUpdateOneRequiredWithoutChannelsNestedInput
}

export type GuildChannelUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuildChannelCreateManyInput = {
  name: string
  id: string
  url: string
  guildId: string
}

export type GuildChannelUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuildChannelUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  guildId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuildChannelListRelationFilter = {
  every?: Prisma.GuildChannelWhereInput
  some?: Prisma.GuildChannelWhereInput
  none?: Prisma.GuildChannelWhereInput
}

export type GuildChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GuildChannelCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
}

export type GuildChannelMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
}

export type GuildChannelMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  guildId?: Prisma.SortOrder
}

export type GuildChannelCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.GuildChannelCreateWithoutGuildInput, Prisma.GuildChannelUncheckedCreateWithoutGuildInput> | Prisma.GuildChannelCreateWithoutGuildInput[] | Prisma.GuildChannelUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.GuildChannelCreateOrConnectWithoutGuildInput | Prisma.GuildChannelCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.GuildChannelCreateManyGuildInputEnvelope
  connect?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
}

export type GuildChannelUncheckedCreateNestedManyWithoutGuildInput = {
  create?: Prisma.XOR<Prisma.GuildChannelCreateWithoutGuildInput, Prisma.GuildChannelUncheckedCreateWithoutGuildInput> | Prisma.GuildChannelCreateWithoutGuildInput[] | Prisma.GuildChannelUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.GuildChannelCreateOrConnectWithoutGuildInput | Prisma.GuildChannelCreateOrConnectWithoutGuildInput[]
  createMany?: Prisma.GuildChannelCreateManyGuildInputEnvelope
  connect?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
}

export type GuildChannelUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.GuildChannelCreateWithoutGuildInput, Prisma.GuildChannelUncheckedCreateWithoutGuildInput> | Prisma.GuildChannelCreateWithoutGuildInput[] | Prisma.GuildChannelUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.GuildChannelCreateOrConnectWithoutGuildInput | Prisma.GuildChannelCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.GuildChannelUpsertWithWhereUniqueWithoutGuildInput | Prisma.GuildChannelUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.GuildChannelCreateManyGuildInputEnvelope
  set?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  disconnect?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  delete?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  connect?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  update?: Prisma.GuildChannelUpdateWithWhereUniqueWithoutGuildInput | Prisma.GuildChannelUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.GuildChannelUpdateManyWithWhereWithoutGuildInput | Prisma.GuildChannelUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.GuildChannelScalarWhereInput | Prisma.GuildChannelScalarWhereInput[]
}

export type GuildChannelUncheckedUpdateManyWithoutGuildNestedInput = {
  create?: Prisma.XOR<Prisma.GuildChannelCreateWithoutGuildInput, Prisma.GuildChannelUncheckedCreateWithoutGuildInput> | Prisma.GuildChannelCreateWithoutGuildInput[] | Prisma.GuildChannelUncheckedCreateWithoutGuildInput[]
  connectOrCreate?: Prisma.GuildChannelCreateOrConnectWithoutGuildInput | Prisma.GuildChannelCreateOrConnectWithoutGuildInput[]
  upsert?: Prisma.GuildChannelUpsertWithWhereUniqueWithoutGuildInput | Prisma.GuildChannelUpsertWithWhereUniqueWithoutGuildInput[]
  createMany?: Prisma.GuildChannelCreateManyGuildInputEnvelope
  set?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  disconnect?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  delete?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  connect?: Prisma.GuildChannelWhereUniqueInput | Prisma.GuildChannelWhereUniqueInput[]
  update?: Prisma.GuildChannelUpdateWithWhereUniqueWithoutGuildInput | Prisma.GuildChannelUpdateWithWhereUniqueWithoutGuildInput[]
  updateMany?: Prisma.GuildChannelUpdateManyWithWhereWithoutGuildInput | Prisma.GuildChannelUpdateManyWithWhereWithoutGuildInput[]
  deleteMany?: Prisma.GuildChannelScalarWhereInput | Prisma.GuildChannelScalarWhereInput[]
}

export type GuildChannelCreateWithoutGuildInput = {
  name: string
  id: string
  url: string
}

export type GuildChannelUncheckedCreateWithoutGuildInput = {
  name: string
  id: string
  url: string
}

export type GuildChannelCreateOrConnectWithoutGuildInput = {
  where: Prisma.GuildChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.GuildChannelCreateWithoutGuildInput, Prisma.GuildChannelUncheckedCreateWithoutGuildInput>
}

export type GuildChannelCreateManyGuildInputEnvelope = {
  data: Prisma.GuildChannelCreateManyGuildInput | Prisma.GuildChannelCreateManyGuildInput[]
  skipDuplicates?: boolean
}

export type GuildChannelUpsertWithWhereUniqueWithoutGuildInput = {
  where: Prisma.GuildChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.GuildChannelUpdateWithoutGuildInput, Prisma.GuildChannelUncheckedUpdateWithoutGuildInput>
  create: Prisma.XOR<Prisma.GuildChannelCreateWithoutGuildInput, Prisma.GuildChannelUncheckedCreateWithoutGuildInput>
}

export type GuildChannelUpdateWithWhereUniqueWithoutGuildInput = {
  where: Prisma.GuildChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.GuildChannelUpdateWithoutGuildInput, Prisma.GuildChannelUncheckedUpdateWithoutGuildInput>
}

export type GuildChannelUpdateManyWithWhereWithoutGuildInput = {
  where: Prisma.GuildChannelScalarWhereInput
  data: Prisma.XOR<Prisma.GuildChannelUpdateManyMutationInput, Prisma.GuildChannelUncheckedUpdateManyWithoutGuildInput>
}

export type GuildChannelScalarWhereInput = {
  AND?: Prisma.GuildChannelScalarWhereInput | Prisma.GuildChannelScalarWhereInput[]
  OR?: Prisma.GuildChannelScalarWhereInput[]
  NOT?: Prisma.GuildChannelScalarWhereInput | Prisma.GuildChannelScalarWhereInput[]
  name?: Prisma.StringFilter<"GuildChannel"> | string
  id?: Prisma.StringFilter<"GuildChannel"> | string
  url?: Prisma.StringFilter<"GuildChannel"> | string
  guildId?: Prisma.StringFilter<"GuildChannel"> | string
}

export type GuildChannelCreateManyGuildInput = {
  name: string
  id: string
  url: string
}

export type GuildChannelUpdateWithoutGuildInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuildChannelUncheckedUpdateWithoutGuildInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}

export type GuildChannelUncheckedUpdateManyWithoutGuildInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
}



export type GuildChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  id?: boolean
  url?: boolean
  guildId?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guildChannel"]>

export type GuildChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  id?: boolean
  url?: boolean
  guildId?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guildChannel"]>

export type GuildChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  id?: boolean
  url?: boolean
  guildId?: boolean
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guildChannel"]>

export type GuildChannelSelectScalar = {
  name?: boolean
  id?: boolean
  url?: boolean
  guildId?: boolean
}

export type GuildChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "id" | "url" | "guildId", ExtArgs["result"]["guildChannel"]>
export type GuildChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}
export type GuildChannelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}
export type GuildChannelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guild?: boolean | Prisma.GuildDefaultArgs<ExtArgs>
}

export type $GuildChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GuildChannel"
  objects: {
    guild: Prisma.$GuildPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    id: string
    url: string
    guildId: string
  }, ExtArgs["result"]["guildChannel"]>
  composites: {}
}

export type GuildChannelGetPayload<S extends boolean | null | undefined | GuildChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload, S>

export type GuildChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuildChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuildChannelCountAggregateInputType | true
  }

export interface GuildChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GuildChannel'], meta: { name: 'GuildChannel' } }
  /**
   * Find zero or one GuildChannel that matches the filter.
   * @param {GuildChannelFindUniqueArgs} args - Arguments to find a GuildChannel
   * @example
   * // Get one GuildChannel
   * const guildChannel = await prisma.guildChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuildChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, GuildChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GuildChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuildChannelFindUniqueOrThrowArgs} args - Arguments to find a GuildChannel
   * @example
   * // Get one GuildChannel
   * const guildChannel = await prisma.guildChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuildChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuildChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuildChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelFindFirstArgs} args - Arguments to find a GuildChannel
   * @example
   * // Get one GuildChannel
   * const guildChannel = await prisma.guildChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuildChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, GuildChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuildChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelFindFirstOrThrowArgs} args - Arguments to find a GuildChannel
   * @example
   * // Get one GuildChannel
   * const guildChannel = await prisma.guildChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuildChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuildChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GuildChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GuildChannels
   * const guildChannels = await prisma.guildChannel.findMany()
   * 
   * // Get first 10 GuildChannels
   * const guildChannels = await prisma.guildChannel.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const guildChannelWithNameOnly = await prisma.guildChannel.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends GuildChannelFindManyArgs>(args?: Prisma.SelectSubset<T, GuildChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GuildChannel.
   * @param {GuildChannelCreateArgs} args - Arguments to create a GuildChannel.
   * @example
   * // Create one GuildChannel
   * const GuildChannel = await prisma.guildChannel.create({
   *   data: {
   *     // ... data to create a GuildChannel
   *   }
   * })
   * 
   */
  create<T extends GuildChannelCreateArgs>(args: Prisma.SelectSubset<T, GuildChannelCreateArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GuildChannels.
   * @param {GuildChannelCreateManyArgs} args - Arguments to create many GuildChannels.
   * @example
   * // Create many GuildChannels
   * const guildChannel = await prisma.guildChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuildChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, GuildChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GuildChannels and returns the data saved in the database.
   * @param {GuildChannelCreateManyAndReturnArgs} args - Arguments to create many GuildChannels.
   * @example
   * // Create many GuildChannels
   * const guildChannel = await prisma.guildChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GuildChannels and only return the `name`
   * const guildChannelWithNameOnly = await prisma.guildChannel.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GuildChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GuildChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GuildChannel.
   * @param {GuildChannelDeleteArgs} args - Arguments to delete one GuildChannel.
   * @example
   * // Delete one GuildChannel
   * const GuildChannel = await prisma.guildChannel.delete({
   *   where: {
   *     // ... filter to delete one GuildChannel
   *   }
   * })
   * 
   */
  delete<T extends GuildChannelDeleteArgs>(args: Prisma.SelectSubset<T, GuildChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GuildChannel.
   * @param {GuildChannelUpdateArgs} args - Arguments to update one GuildChannel.
   * @example
   * // Update one GuildChannel
   * const guildChannel = await prisma.guildChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuildChannelUpdateArgs>(args: Prisma.SelectSubset<T, GuildChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GuildChannels.
   * @param {GuildChannelDeleteManyArgs} args - Arguments to filter GuildChannels to delete.
   * @example
   * // Delete a few GuildChannels
   * const { count } = await prisma.guildChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuildChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuildChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuildChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GuildChannels
   * const guildChannel = await prisma.guildChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuildChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, GuildChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuildChannels and returns the data updated in the database.
   * @param {GuildChannelUpdateManyAndReturnArgs} args - Arguments to update many GuildChannels.
   * @example
   * // Update many GuildChannels
   * const guildChannel = await prisma.guildChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GuildChannels and only return the `name`
   * const guildChannelWithNameOnly = await prisma.guildChannel.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GuildChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GuildChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GuildChannel.
   * @param {GuildChannelUpsertArgs} args - Arguments to update or create a GuildChannel.
   * @example
   * // Update or create a GuildChannel
   * const guildChannel = await prisma.guildChannel.upsert({
   *   create: {
   *     // ... data to create a GuildChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GuildChannel we want to update
   *   }
   * })
   */
  upsert<T extends GuildChannelUpsertArgs>(args: Prisma.SelectSubset<T, GuildChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__GuildChannelClient<runtime.Types.Result.GetResult<Prisma.$GuildChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GuildChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelCountArgs} args - Arguments to filter GuildChannels to count.
   * @example
   * // Count the number of GuildChannels
   * const count = await prisma.guildChannel.count({
   *   where: {
   *     // ... the filter for the GuildChannels we want to count
   *   }
   * })
  **/
  count<T extends GuildChannelCountArgs>(
    args?: Prisma.Subset<T, GuildChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuildChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GuildChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuildChannelAggregateArgs>(args: Prisma.Subset<T, GuildChannelAggregateArgs>): Prisma.PrismaPromise<GetGuildChannelAggregateType<T>>

  /**
   * Group by GuildChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuildChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuildChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuildChannelGroupByArgs['orderBy'] }
      : { orderBy?: GuildChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuildChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuildChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GuildChannel model
 */
readonly fields: GuildChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GuildChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuildChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guild<T extends Prisma.GuildDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuildDefaultArgs<ExtArgs>>): Prisma.Prisma__GuildClient<runtime.Types.Result.GetResult<Prisma.$GuildPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GuildChannel model
 */
export interface GuildChannelFieldRefs {
  readonly name: Prisma.FieldRef<"GuildChannel", 'String'>
  readonly id: Prisma.FieldRef<"GuildChannel", 'String'>
  readonly url: Prisma.FieldRef<"GuildChannel", 'String'>
  readonly guildId: Prisma.FieldRef<"GuildChannel", 'String'>
}
    

// Custom InputTypes
/**
 * GuildChannel findUnique
 */
export type GuildChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * Filter, which GuildChannel to fetch.
   */
  where: Prisma.GuildChannelWhereUniqueInput
}

/**
 * GuildChannel findUniqueOrThrow
 */
export type GuildChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * Filter, which GuildChannel to fetch.
   */
  where: Prisma.GuildChannelWhereUniqueInput
}

/**
 * GuildChannel findFirst
 */
export type GuildChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * Filter, which GuildChannel to fetch.
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildChannels to fetch.
   */
  orderBy?: Prisma.GuildChannelOrderByWithRelationInput | Prisma.GuildChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuildChannels.
   */
  cursor?: Prisma.GuildChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuildChannels.
   */
  distinct?: Prisma.GuildChannelScalarFieldEnum | Prisma.GuildChannelScalarFieldEnum[]
}

/**
 * GuildChannel findFirstOrThrow
 */
export type GuildChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * Filter, which GuildChannel to fetch.
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildChannels to fetch.
   */
  orderBy?: Prisma.GuildChannelOrderByWithRelationInput | Prisma.GuildChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuildChannels.
   */
  cursor?: Prisma.GuildChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuildChannels.
   */
  distinct?: Prisma.GuildChannelScalarFieldEnum | Prisma.GuildChannelScalarFieldEnum[]
}

/**
 * GuildChannel findMany
 */
export type GuildChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * Filter, which GuildChannels to fetch.
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuildChannels to fetch.
   */
  orderBy?: Prisma.GuildChannelOrderByWithRelationInput | Prisma.GuildChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GuildChannels.
   */
  cursor?: Prisma.GuildChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuildChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuildChannels.
   */
  skip?: number
  distinct?: Prisma.GuildChannelScalarFieldEnum | Prisma.GuildChannelScalarFieldEnum[]
}

/**
 * GuildChannel create
 */
export type GuildChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a GuildChannel.
   */
  data: Prisma.XOR<Prisma.GuildChannelCreateInput, Prisma.GuildChannelUncheckedCreateInput>
}

/**
 * GuildChannel createMany
 */
export type GuildChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GuildChannels.
   */
  data: Prisma.GuildChannelCreateManyInput | Prisma.GuildChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GuildChannel createManyAndReturn
 */
export type GuildChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * The data used to create many GuildChannels.
   */
  data: Prisma.GuildChannelCreateManyInput | Prisma.GuildChannelCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GuildChannel update
 */
export type GuildChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a GuildChannel.
   */
  data: Prisma.XOR<Prisma.GuildChannelUpdateInput, Prisma.GuildChannelUncheckedUpdateInput>
  /**
   * Choose, which GuildChannel to update.
   */
  where: Prisma.GuildChannelWhereUniqueInput
}

/**
 * GuildChannel updateMany
 */
export type GuildChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GuildChannels.
   */
  data: Prisma.XOR<Prisma.GuildChannelUpdateManyMutationInput, Prisma.GuildChannelUncheckedUpdateManyInput>
  /**
   * Filter which GuildChannels to update
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * Limit how many GuildChannels to update.
   */
  limit?: number
}

/**
 * GuildChannel updateManyAndReturn
 */
export type GuildChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * The data used to update GuildChannels.
   */
  data: Prisma.XOR<Prisma.GuildChannelUpdateManyMutationInput, Prisma.GuildChannelUncheckedUpdateManyInput>
  /**
   * Filter which GuildChannels to update
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * Limit how many GuildChannels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GuildChannel upsert
 */
export type GuildChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the GuildChannel to update in case it exists.
   */
  where: Prisma.GuildChannelWhereUniqueInput
  /**
   * In case the GuildChannel found by the `where` argument doesn't exist, create a new GuildChannel with this data.
   */
  create: Prisma.XOR<Prisma.GuildChannelCreateInput, Prisma.GuildChannelUncheckedCreateInput>
  /**
   * In case the GuildChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuildChannelUpdateInput, Prisma.GuildChannelUncheckedUpdateInput>
}

/**
 * GuildChannel delete
 */
export type GuildChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
  /**
   * Filter which GuildChannel to delete.
   */
  where: Prisma.GuildChannelWhereUniqueInput
}

/**
 * GuildChannel deleteMany
 */
export type GuildChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuildChannels to delete
   */
  where?: Prisma.GuildChannelWhereInput
  /**
   * Limit how many GuildChannels to delete.
   */
  limit?: number
}

/**
 * GuildChannel without action
 */
export type GuildChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuildChannel
   */
  select?: Prisma.GuildChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuildChannel
   */
  omit?: Prisma.GuildChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuildChannelInclude<ExtArgs> | null
}
